server:
  port: 8888
spring:
  application:
    name: admin
  datasource:
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      hikari:
        username: root
        password: lmc@2017
        driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.user.entity

dubbo:
  protocol:
    port: 20889
    name: dubbo
  registry:
    address: spring-cloud://127.0.0.1:8848
  cloud:
    subscribed-services: product
  application:
    name: admin