server:
  port: 8889
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: product
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848

dubbo:
  scan:
    base-packages: org.product.service.impl
  protocol:
    port: 20899
    name: dubbo
  registry:
    address: spring-cloud://127.0.0.1:8848
  application:
    name: registry
